image: microsoft/dotnet:latest

stages:
    - build
    - package

build:
    stage: build
    script:
        - "dotnet build"
    artifacts:
      paths:
        - bin/

package_to_docker_image:
    stage: package
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -f "src/App/Dockerfile" -t registry.gitlab.com/wachirawitc/liff-app .
        - docker push registry.gitlab.com/wachirawitc/liff-app
